<!DOCTYPE html>
<html>

<head>
  <title>Text-to-Speech Converter</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      background-color: #f5f5f5;
      font-family: sans-serif;
    }

    #container {
      max-width: 600px;
      margin: 0 auto;
      text-align: center;
      padding: 20px;
      background-color: #ffffff;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
      font-size: 2em;
      margin-bottom: 20px;
    }

    label {
      display: block;
      margin-bottom: 10px;
      font-size: 1.2em;
    }

    textarea {
      width: 100%;
      height: 150px;
      margin-bottom: 20px;
      font-size: 1.2em;
      padding: 10px;
      border: 1px solid #cccccc;
    }

    select {
      font-size: 1.2em;
      padding: 10px;
      margin-bottom: 20px;
      border: 1px solid #cccccc;
    }

    input[type="submit"] {
      background-color: #007bff;
      color: #ffffff;
      font-size: 1.2em;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
      margin: 1rem;
    }

    input[type="submit"]:hover {
      background-color: #0056b3;
    }

    .author {
      margin-top: 20px;
      font-size: 0.8em;
      color: #999999;
    }
  </style>
</head>

<body>
  <div id="container">
    <h1>Text-to-Speech Converter</h1>
    <form method="post">
      <label for="txt">Enter Text:</label>
      <textarea id="txt" name="txt"></textarea><br>
      <label for="lang">Select Language:</label>
      <select id="lang" name="lang">
        <option value="en-US" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'en-US') echo 'selected'; ?>>English (US)</option>
        <option value="en-GB" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'en-GB') echo 'selected'; ?>>English (UK)</option>
        <option value="fr-FR" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'fr-FR') echo 'selected'; ?>>French</option>
        <option value="de-DE" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'de-DE') echo 'selected'; ?>>German</option>
        <option value="es-ES" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'es-ES') echo 'selected'; ?>>Spanish</option>
        <option value="it-IT" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'it-IT') echo 'selected'; ?>>Italian</option>
        <option value="ja-JP" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'ja-JP') echo 'selected'; ?>>Japanese</option>
        <option value="ko-KR" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'ko-KR') echo 'selected'; ?>>Korean</option>
        <option value="zh-CN" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'zh-CN') echo 'selected'; ?>>Chinese (Simplified)</option>
        <option value="ru-RU" <?php if (isset($_COOKIE['lang']) && $_COOKIE['lang'] == 'ru-RU') echo 'selected'; ?>>Russian</option>
        <br>
      </select>

      <input name="submit" type="submit" value="Convert to Speech"><br>
    </form>


    <?php
    $lang = isset($_COOKIE['lang']) ? $_COOKIE['lang'] : 'en';
    if (isset($_POST['txt'])) {
      $txt = $_POST['txt'];
      $txt = htmlspecialchars($txt);
      $txt = rawurlencode($txt);

      $audio = file_get_contents('https://translate.google.com/translate_tts?ie=UTF-8&client=gtx&q=' . $txt . '&tl=' . $lang);
      $speech = "<audio controls='controls'><source src='data:audio/mpeg;base64," . base64_encode($audio) . "'></audio>";

      $author = "Generated by Yomi using CHATgpt";
    }
    if (isset($_POST['lang'])) {
      $lang = $_POST['lang'];
      setcookie('lang', $lang, time() + (86400 * 30), "/"); // store cookie for 30 days
    }
    echo $speech;
    ?>